framework:
    validation:
<<<<<<< HEAD
=======
        email_validation_mode: html5

>>>>>>> dd238d0bf7bf109232031f042ecf1572bb2c662b
        # Enables validator auto-mapping support.
        # For instance, basic validation constraints will be inferred from Doctrine's metadata.
        #auto_mapping:
        #    App\Entity\: []

when@test:
    framework:
        validation:
            not_compromised_password: false
